CREATE TABLE authorities
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    user_id INTEGER,
    CONSTRAINT pk_authorities PRIMARY KEY (id)
);

CREATE TABLE match
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    tournament_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_match PRIMARY KEY (id)
);

CREATE TABLE match_map
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    result_team_one INTEGER                                 NOT NULL,
    result_team_two INTEGER                                 NOT NULL,
    ct_one          INTEGER                                 NOT NULL,
    ct_two          INTEGER                                 NOT NULL,
    t_one           INTEGER                                 NOT NULL,
    t_two           INTEGER                                 NOT NULL,
    rank_one        INTEGER                                 NOT NULL,
    rank_two        INTEGER                                 NOT NULL,
    map_wins_one    INTEGER                                 NOT NULL,
    map_wins_two    INTEGER                                 NOT NULL,
    map_winner      INTEGER                                 NOT NULL,
    match_id        BIGINT,
    CONSTRAINT pk_match_map PRIMARY KEY (id)
);

CREATE TABLE tournament
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tournament PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255)                             NOT NULL,
    email    VARCHAR(255)                             NOT NULL,
    role     VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE authorities
    ADD CONSTRAINT FK_AUTHORITIES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE match_map
    ADD CONSTRAINT FK_MATCH_MAP_ON_MATCH FOREIGN KEY (match_id) REFERENCES match (id);

ALTER TABLE match
    ADD CONSTRAINT FK_MATCH_ON_TOURNAMENT FOREIGN KEY (tournament_id) REFERENCES tournament (id);